// Code generated by MockGen. DO NOT EDIT.
// Source: ./connection.go
//
// Generated by this command:
//
//	mockgen -source=./connection.go -destination=./connection_mock.go -package=nntpcli Connection
//

// Package nntpcli is a generated GoMock package.
package nntpcli

import (
	io "io"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockConnection is a mock of Connection interface.
type MockConnection struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionMockRecorder
	isgomock struct{}
}

// MockConnectionMockRecorder is the mock recorder for MockConnection.
type MockConnectionMockRecorder struct {
	mock *MockConnection
}

// NewMockConnection creates a new mock instance.
func NewMockConnection(ctrl *gomock.Controller) *MockConnection {
	mock := &MockConnection{ctrl: ctrl}
	mock.recorder = &MockConnectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnection) EXPECT() *MockConnectionMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockConnection) Authenticate(username, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", username, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockConnectionMockRecorder) Authenticate(username, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockConnection)(nil).Authenticate), username, password)
}

// BodyDecoded mocks base method.
func (m *MockConnection) BodyDecoded(msgID string, w io.Writer, discard int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BodyDecoded", msgID, w, discard)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BodyDecoded indicates an expected call of BodyDecoded.
func (mr *MockConnectionMockRecorder) BodyDecoded(msgID, w, discard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BodyDecoded", reflect.TypeOf((*MockConnection)(nil).BodyDecoded), msgID, w, discard)
}

// BodyReader mocks base method.
func (m *MockConnection) BodyReader(msgID string) (ArticleBodyReader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BodyReader", msgID)
	ret0, _ := ret[0].(ArticleBodyReader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BodyReader indicates an expected call of BodyReader.
func (mr *MockConnectionMockRecorder) BodyReader(msgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BodyReader", reflect.TypeOf((*MockConnection)(nil).BodyReader), msgID)
}

// Capabilities mocks base method.
func (m *MockConnection) Capabilities() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Capabilities")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Capabilities indicates an expected call of Capabilities.
func (mr *MockConnectionMockRecorder) Capabilities() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Capabilities", reflect.TypeOf((*MockConnection)(nil).Capabilities))
}

// Close mocks base method.
func (m *MockConnection) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockConnectionMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockConnection)(nil).Close))
}

// CurrentJoinedGroup mocks base method.
func (m *MockConnection) CurrentJoinedGroup() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentJoinedGroup")
	ret0, _ := ret[0].(string)
	return ret0
}

// CurrentJoinedGroup indicates an expected call of CurrentJoinedGroup.
func (mr *MockConnectionMockRecorder) CurrentJoinedGroup() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentJoinedGroup", reflect.TypeOf((*MockConnection)(nil).CurrentJoinedGroup))
}

// GetMetrics mocks base method.
func (m *MockConnection) GetMetrics() *Metrics {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetrics")
	ret0, _ := ret[0].(*Metrics)
	return ret0
}

// GetMetrics indicates an expected call of GetMetrics.
func (mr *MockConnectionMockRecorder) GetMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetrics", reflect.TypeOf((*MockConnection)(nil).GetMetrics))
}

// JoinGroup mocks base method.
func (m *MockConnection) JoinGroup(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinGroup", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// JoinGroup indicates an expected call of JoinGroup.
func (mr *MockConnectionMockRecorder) JoinGroup(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinGroup", reflect.TypeOf((*MockConnection)(nil).JoinGroup), name)
}

// MaxAgeTime mocks base method.
func (m *MockConnection) MaxAgeTime() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxAgeTime")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// MaxAgeTime indicates an expected call of MaxAgeTime.
func (mr *MockConnectionMockRecorder) MaxAgeTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxAgeTime", reflect.TypeOf((*MockConnection)(nil).MaxAgeTime))
}

// Post mocks base method.
func (m *MockConnection) Post(r io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Post", r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Post indicates an expected call of Post.
func (mr *MockConnectionMockRecorder) Post(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Post", reflect.TypeOf((*MockConnection)(nil).Post), r)
}

// Stat mocks base method.
func (m *MockConnection) Stat(msgID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat", msgID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *MockConnectionMockRecorder) Stat(msgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockConnection)(nil).Stat), msgID)
}
