package nzb

import (
	"bytes"
	"encoding/binary"
	"strings"
	"testing"
)

func TestFileFileName(t *testing.T) {
	tests := []struct {
		subject string
		want    string
	}{
		{`[01/66] - "nova.s44e02.720p-dhd.r00" yEnc (01/66)`, "nova.s44e02.720p-dhd.r00"},
		{`"simple.nfo" yEnc (1/1)`, "simple.nfo"},
		{`no quotes here`, ""},
		{`"unclosed`, ""},
		{`[1/1] - "release.srr" yEnc (1/1)`, "release.srr"},
	}
	for _, tc := range tests {
		f := File{Subject: tc.subject}
		got := f.FileName()
		if got != tc.want {
			t.Errorf("FileName(%q) = %q, want %q", tc.subject, got, tc.want)
		}
	}
}

func TestNZBSRRFile(t *testing.T) {
	nzbXML := `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE nzb PUBLIC "-//newzBin//DTD NZB 1.0//EN" "http://www.newzbin.com/DTD/nzb/nzb-1.0.dtd">
<nzb xmlns="urn:newzbin:nzb:1.0">
  <file poster="test" date="1234567890" subject="[1/3] - &quot;nova.s44e02.720p-dhd.srr&quot; yEnc (1/1)">
    <groups><group>alt.binaries.test</group></groups>
    <segments><segment bytes="100" number="1">abc@def</segment></segments>
  </file>
  <file poster="test" date="1234567890" subject="[2/3] - &quot;nova.s44e02.720p-dhd.r00&quot; yEnc (1/66)">
    <groups><group>alt.binaries.test</group></groups>
    <segments><segment bytes="100" number="1">ghi@jkl</segment></segments>
  </file>
</nzb>`
	n, err := Parse(strings.NewReader(nzbXML))
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	f := n.SRRFile()
	if f == nil {
		t.Fatal("SRRFile() returned nil, want non-nil")
	}
	name := f.FileName()
	if !strings.HasSuffix(strings.ToLower(name), ".srr") {
		t.Errorf("SRRFile().FileName() = %q, want .srr suffix", name)
	}
}

func TestNZBSRRFileNone(t *testing.T) {
	nzbXML := `<?xml version="1.0" encoding="UTF-8"?>
<nzb xmlns="urn:newzbin:nzb:1.0">
  <file poster="test" date="1234567890" subject="[1/1] - &quot;file.r00&quot; yEnc (1/1)">
    <groups><group>alt.binaries.test</group></groups>
    <segments><segment bytes="100" number="1">abc@def</segment></segments>
  </file>
</nzb>`
	n, err := Parse(strings.NewReader(nzbXML))
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if f := n.SRRFile(); f != nil {
		t.Errorf("SRRFile() = %v, want nil", f)
	}
}

// buildSRRMarker returns the 7-byte SRR marker block (magic 0x69 0x69 0x69).
func buildSRRMarker() []byte {
	// HEAD_CRC=0x6969, HEAD_TYPE=0x69, HEAD_FLAGS=0x0000, HEAD_SIZE=7
	return []byte{0x69, 0x69, 0x69, 0x00, 0x00, 0x07, 0x00}
}

// buildStoredFileBlock builds a 0x6A stored-file block with the given
// filename and file content.
func buildStoredFileBlock(fname string, content []byte) []byte {
	var buf bytes.Buffer
	fnameBytes := []byte(fname)
	// body = fname_len(2) + fname bytes
	bodySize := 2 + len(fnameBytes)
	// HEAD_SIZE includes base(7) + ADD_SIZE field(4) + body
	headSize := uint16(7 + 4 + bodySize)
	headFlags := uint16(0x8000) // has ADD_SIZE
	addSize := uint32(len(content))

	buf.Write([]byte{0x00, 0x00}) // HEAD_CRC (arbitrary for tests)
	buf.WriteByte(0x6A)           // HEAD_TYPE
	_ = binary.Write(&buf, binary.LittleEndian, headFlags)
	_ = binary.Write(&buf, binary.LittleEndian, headSize)
	_ = binary.Write(&buf, binary.LittleEndian, addSize)
	_ = binary.Write(&buf, binary.LittleEndian, uint16(len(fnameBytes)))
	buf.Write(fnameBytes)
	buf.Write(content)
	return buf.Bytes()
}

func TestParseSRRFilenames_Synthetic(t *testing.T) {
	sfvContent := "; generated by test\nfile.r00 AABBCCDD\nfile.rar E1E2E3E4\n"
	nfoContent := "some nfo text"

	var srrBuf bytes.Buffer
	srrBuf.Write(buildSRRMarker())
	srrBuf.Write(buildStoredFileBlock("release.nfo", []byte(nfoContent)))
	srrBuf.Write(buildStoredFileBlock("release.sfv", []byte(sfvContent)))

	names, err := ParseSRRFilenames(&srrBuf)
	if err != nil {
		t.Fatalf("ParseSRRFilenames: %v", err)
	}

	want := map[string]bool{
		"release.nfo": true,
		"release.sfv": true,
		"file.r00":    true,
		"file.rar":    true,
	}
	for _, name := range names {
		delete(want, name)
	}
	if len(want) > 0 {
		missing := make([]string, 0, len(want))
		for k := range want {
			missing = append(missing, k)
		}
		t.Errorf("missing filenames: %v (got: %v)", missing, names)
	}
}

func TestParseSRRFilenames_InvalidMagic(t *testing.T) {
	_, err := ParseSRRFilenames(bytes.NewReader([]byte{0x00, 0x01, 0x02, 0x03}))
	if err == nil {
		t.Error("expected error for invalid magic, got nil")
	}
}

func TestParseSRRFilenames_Dedup(t *testing.T) {
	sfvContent := "file.r00 AABBCCDD\nfile.r00 AABBCCDD\n" // duplicate in SFV
	var srrBuf bytes.Buffer
	srrBuf.Write(buildSRRMarker())
	srrBuf.Write(buildStoredFileBlock("release.sfv", []byte(sfvContent)))

	names, err := ParseSRRFilenames(&srrBuf)
	if err != nil {
		t.Fatalf("ParseSRRFilenames: %v", err)
	}
	seen := make(map[string]int)
	for _, n := range names {
		seen[n]++
	}
	for name, count := range seen {
		if count > 1 {
			t.Errorf("filename %q appears %d times, want 1", name, count)
		}
	}
}
